
# Script for processing raw CIPHA DynAirX data into workable format.

## Loading raw data

raw_extr_path <- "C:/Users/elliot.royle/OneDrive - Midlands and Lancashire CSU/Git/Primary-Care-Theograph/data/raw_extracts/Raw_Patient_Extract.csv"
raw_extr_df <- read.csv(raw_extr_path, header = TRUE)


## Splitting main data file into various subsets for visualisation

raw_extr_df_filter <-  raw_extr_df %>%
  filter(term %in% c("Lying diastolic blood pressure (observable entity)",
                     "Lying systolic blood pressure (observable entity)",
                     "Renal profile (observable entity)",
                     "Serum low density lipoprotein cholesterol level (observable entity)",
                     "Haemoglobin A1c level - International Federation of Clinical Chemistry and Laboratory Medicine standardised (observable entity)",
                     "Essential hypertension (disorder)",
                     "Constipation (disorder)",
                     "Diabetes mellitus type 2 (disorder)",
                     "Chronic obstructive lung disease (disorder)",
                     "Mixed anxiety and depressive disorder (disorder)",
                     "Depressive disorder NEC (disorder)",
                     "Depressive disorder (disorder)",
                     "Atorvastatin 10mg tablets",
                     "Atorvastatin 20mg tablets",
                     "Atorvastatin 40mg tablets",
                     "Atorvastatin 60mg tablets",
                     "Bisacodyl 5mg gastro-resistant tablets",
                     "Bisoprolol 1.25mg tablets",
                     "Bisoprolol 10mg tablets",
                     "Bisoprolol 2.5mg tablets",
                     "Bisoprolol 5mg tablets",
                     "Candesartan 4mg tablets",
                     "Candesartan 8mg tablets",
                     "Citalopram 10mg tablets",                     
                     "Citalopram 20mg tablets",
                     "Escitalopram 10mg tablets",
                     "Flucloxacillin 500mg capsules",
                     "Fluconazole 150mg capsules")) %>%
  mutate(Contact_Record_Category = case_when(
    term %in% c("Lying diastolic blood pressure (observable entity)",
                "Lying systolic blood pressure (observable entity)",
                "Renal profile (observable entity)",
                "Serum low density lipoprotein cholesterol level (observable entity)",
                "Haemoglobin A1c level - International Federation of Clinical Chemistry and Laboratory Medicine standardised (observable entity)") ~ "Biomedical Assay",
    term %in% c("Essential hypertension (disorder)",
                "Constipation (disorder)",
                "Diabetes mellitus type 2 (disorder)",
                "Chronic obstructive lung disease (disorder)",
                "Mixed anxiety and depressive disorder (disorder)",
                "Depressive disorder NEC (disorder)",
                "Depressive disorder (disorder)") ~ "Diagnosis/Review",
    term %in% c("Atorvastatin 10mg tablets",
                "Atorvastatin 20mg tablets",
                "Atorvastatin 40mg tablets",
                "Atorvastatin 60mg tablets",
                "Bisacodyl 5mg gastro-resistant tablets",
                "Bisoprolol 1.25mg tablets",
                "Bisoprolol 10mg tablets",
                "Bisoprolol 2.5mg tablets",
                "Bisoprolol 5mg tablets",
                "Candesartan 4mg tablets",
                "Candesartan 8mg tablets",
                "Citalopram 10mg tablets",                     
                "Citalopram 20mg tablets",
                "Escitalopram 10mg tablets",
                "Flucloxacillin 500mg capsules",
                "Fluconazole 150mg capsules") ~ "Medication",
    TRUE ~ "NotKnown")) %>%
  mutate(units = case_when(
    !is.na(units) ~ units,
    term %in% c("Atorvastatin 10mg tablets",
                "Atorvastatin 20mg tablets",
                "Atorvastatin 40mg tablets",
                "Atorvastatin 60mg tablets",
                "Bisacodyl 5mg gastro-resistant tablets",
                "Bisoprolol 1.25mg tablets",
                "Bisoprolol 10mg tablets",
                "Bisoprolol 2.5mg tablets",
                "Bisoprolol 5mg tablets",
                "Candesartan 4mg tablets",
                "Candesartan 8mg tablets",
                "Citalopram 10mg tablets",                     
                "Citalopram 20mg tablets",
                "Escitalopram 10mg tablets",
                "Flucloxacillin 500mg capsules",
                "Fluconazole 150mg capsules") ~ "mg",
    TRUE ~ units)) %>%
  mutate(value = case_when(
    term == "Atorvastatin 10mg tablets" ~ "10",
    term == "Atorvastatin 20mg tablets" ~ "20",
    term == "Atorvastatin 40mg tablets" ~ "40",
    term == "Atorvastatin 60mg tablets" ~ "60",
    term == "Bisacodyl 5mg gastro-resistant tablets" ~ "5",
    term == "Bisoprolol 1.25mg tablets" ~ "1.25",
    term == "Bisoprolol 10mg tablets" ~ "10",
    term == "Bisoprolol 2.5mg tablets" ~ "2.5",
    term == "Bisoprolol 5mg tablets" ~ "5",
    term == "Candesartan 4mg tablets" ~ "4",
    term == "Candesartan 8mg tablets" ~ "8",
    term == "Citalopram 10mg tablets" ~ "10",                     
    term == "Citalopram 20mg tablets" ~ "20",
    term == "Escitalopram 10mg tablets" ~ "10",
    term == "Flucloxacillin 500mg capsules" ~ "500",
    term == "Fluconazole 150mg capsules"  ~ "150",
    TRUE ~ value)) %>%
  mutate(Contact_Event_Term = case_when(
    term == "Lying diastolic blood pressure (observable entity)" ~ "Lying diastolic BP",
    term == "Lying systolic blood pressure (observable entity)" ~ "Lying systolic BP",
    term == "Renal profile (observable entity)" ~ "Renal profile",
    term == "Serum low density lipoprotein cholesterol level (observable entity)" ~ "Serum LDL chol. level",
    term == "Haemoglobin A1c level - International Federation of Clinical Chemistry and Laboratory Medicine standardised (observable entity)" ~ "HbA1c level",
    term == "Essential hypertension (disorder)" ~ "Essential hypertension",
    term == "Constipation (disorder)" ~ "Constipation",
    term == "Diabetes mellitus type 2 (disorder)" ~ "Diabetes type 2",
    term == "Chronic obstructive lung disease (disorder)" ~ "COLD",
    term == "Mixed anxiety and depressive disorder (disorder)" ~ "Depressive Disorders",
    term == "Depressive disorder NEC (disorder)" ~ "Depressive Disorders",
    term == "Depressive disorder (disorder)" ~ "Depressive Disorders",
    TRUE ~ term)) %>%
  mutate(Patient_Name = case_when(
    PK_Patient_ID == "610673" ~ "Olivia Davies",
    PK_Patient_ID == "2377686" ~ "Matiur Khan",
    PK_Patient_ID == "1684031" ~ "Thomas Williams",
    PK_Patient_ID == "1719111" ~ "Param Patel",
    PK_Patient_ID == "714765" ~ "Leah O'Sullivan",
    PK_Patient_ID == "5329931" ~ "Emily Johnson",
    PK_Patient_ID == "2337077" ~ "Debelah Oluwaseyi",
    PK_Patient_ID == "2813256" ~ "Maya Ahmed",
    PK_Patient_ID == "5162922" ~ "Jack Murphy",
    PK_Patient_ID == "3055848" ~ "Zara Singh",
    PK_Patient_ID == "5182896" ~ "Georgina Taylor",
    PK_Patient_ID == "2839091" ~ "Leila Hassan",
    PK_Patient_ID == "2701908" ~ "William Edwards",
    PK_Patient_ID == "509825" ~ "Stephen Bakhshi",
    PK_Patient_ID == "2752409" ~ "Danielle Roberts",
    PK_Patient_ID == "4822061" ~ "Rhea Desai",
    PK_Patient_ID == "5330850" ~ "Harriet Evans",
    PK_Patient_ID == "3359779" ~ "Amara Nwachukwu",
    PK_Patient_ID == "1920086" ~ "Isla Campbell",
    PK_Patient_ID == "3293167" ~ "Saesha Sharma",
    TRUE ~ "NotKnown")) %>%
  mutate(Patient_Gender = case_when(
    Sex == "M" ~ "Male",
    Sex == "F" ~ "Female",
    TRUE ~ "NotKnown")) %>%
  rename(Patient_DOB = Dob,
         Contact_Event_Date = date,
         Prescription_Instruction = Episodicity,
         Value = value,
         Units = units,
         Contact_Event_Category = eventtype) %>%
  select(13, 14, 3, 5, 11, 12, 9, 10, 8)
